/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alfaclinica;

/**
 *
 * @author letic
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AgendarConsuta = new javax.swing.JButton();
        ConsultaAgendada = new javax.swing.JButton();
        BotaoAgendarExame = new javax.swing.JButton();
        BotaoExamesAgendados = new javax.swing.JButton();
        BotaoPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Bem vindo!");

        AgendarConsuta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgendarConsuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cadastro_64.png"))); // NOI18N
        AgendarConsuta.setText("Agendar Consulta");
        AgendarConsuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarConsutaActionPerformed(evt);
            }
        });

        ConsultaAgendada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConsultaAgendada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agenda.png"))); // NOI18N
        ConsultaAgendada.setText("Consultas agendadas");
        ConsultaAgendada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAgendadaActionPerformed(evt);
            }
        });

        BotaoAgendarExame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoAgendarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exame-de-saude.png"))); // NOI18N
        BotaoAgendarExame.setText("Agendar exame");
        BotaoAgendarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarExameActionPerformed(evt);
            }
        });

        BotaoExamesAgendados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoExamesAgendados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exame.png"))); // NOI18N
        BotaoExamesAgendados.setText("Exames agendados");
        BotaoExamesAgendados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExamesAgendadosActionPerformed(evt);
            }
        });

        BotaoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/do-utilizador.png"))); // NOI18N
        BotaoPerfil.setText("Sair");
        BotaoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoAgendarExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgendarConsuta, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsultaAgendada, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(BotaoExamesAgendados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BotaoPerfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotaoPerfil)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgendarConsuta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultaAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAgendarExame, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoExamesAgendados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgendarConsutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarConsutaActionPerformed
        // TODO add your handling code here:
    AgendarConsulta consulta = new AgendarConsulta();
    this.dispose();
    }//GEN-LAST:event_AgendarConsutaActionPerformed

    private void BotaoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPerfilActionPerformed
        // TODO add your handling code here:
        Perfil usuario = new Perfil();
        this.dispose();
    }//GEN-LAST:event_BotaoPerfilActionPerformed

    private void ConsultaAgendadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAgendadaActionPerformed
        // TODO add your handling code here:
        ConsultaAgendada agendada = new ConsultaAgendada();
        this.dispose();
    }//GEN-LAST:event_ConsultaAgendadaActionPerformed

    private void BotaoAgendarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarExameActionPerformed
        // TODO add your handling code here:
        AgendarExame agendarExame = new AgendarExame();
        this.dispose();
    }//GEN-LAST:event_BotaoAgendarExameActionPerformed

    private void BotaoExamesAgendadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExamesAgendadosActionPerformed
        // TODO add your handling code here:
        ExamesAgendados examesAgendados = new ExamesAgendados();
        this.dispose();
    }//GEN-LAST:event_BotaoExamesAgendadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarConsuta;
    private javax.swing.JButton BotaoAgendarExame;
    private javax.swing.JButton BotaoExamesAgendados;
    private javax.swing.JButton BotaoPerfil;
    private javax.swing.JButton ConsultaAgendada;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
